#logging.level.org.springframework.cloud.gateway=TRACE
#management.endpoints.web.exposure.include=*

resources:
  tenant: ${TENANT}

logging:
  level:
    org.springframework.cloud.gateway: TRACE

spring:
  cloud:
    gateway:
      routes:

        - id: route1
          uri: ${resources.tenant}
          predicates:
            - Path=/sso2/api/users/**
            - Method=GET
          filters:
            - RewritePath=/sso2/(?<segment>.*), /$\{segment}

        - id: route2
          uri: ${resources.tenant}
          predicates:
            - Path=/get/{id}
            - Method=GET
          filters:
            - RedirectTo=302, http://httpbin.org/get